### ISSUE TITLE
SVG formats for emoji are the Android 4.4 versions when they should be Android 7.1

### ISSUE THREAD

**Issue by moskyb** [googlei18n/noto-emoji#79] opened 2016-10-21 23:44 UTC
Compare [this](http://emojipedia-us.s3.amazonaws.com/cache/12/ac/12ac5a6b5ca7289989977a0020020cb4.png) to [this](https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f44f.svg)

**Comment by dougfelt** [comment] 2016-10-22 01:53
duplicate of #30

**Closed by dougfelt** 2016-10-22 01:53 UTC
