### ISSUE TITLE
some svg files are missing

### ISSUE THREAD

**Issue by liudanking** [googlei18n/noto-emoji#133] opened 2017-05-20 06:40 UTC
I find that I can't find some emoji svg files. Below are some of them:

emoji_u1f923.svg
emoji_u1f917.svg
emoji_u1f929.svg
emoji_u1f914.svg

where can I find the missing svg files?

**Comment by asturur** [comment] 2017-05-20 09:16
probably duplicatr of #119

**Comment by DeeDeeG** [comment] 2017-05-20 16:06
These are listed in issue 119...

Except for 1f929, "star-struck," which is new in Emoji 5.0 and isn't
supported yet by any of the major Emoji fonts.

http://unicode.org/emoji/charts/full-emoji-list.html#1f929

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dougfelt** [comment] 2017-05-21 23:41
duplicate of #119

**Closed by dougfelt** 2017-05-21 23:41 UTC
