### ISSUE TITLE
I'm having this issue

### ISSUE THREAD

**Issue by jorgeliecer** [googlei18n/noto-emoji#67] opened 2016-09-07 23:10 UTC
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'cmap' table...
Parsing 'name' table...
Parsing 'post' table...
Looking for images matching 'build/compressed_pngs/emoji_u*.png'.
Traceback (most recent call last):
  File "third_party/color_emoji/add_glyphs.py", line 130, in <module>
    u = codes_to_string(codes)
  File "third_party/color_emoji/add_glyphs.py", line 32, in codes_to_string
    raise ValueError("uh-oh, no unichr for '%s'" % codes)
ValueError: uh-oh, no unichr for '1f004'

**Comment by dougfelt** [comment] 2016-09-07 23:26
My guess is you're using a narrow build of python that doesn't support codepoints past plane 0.  For example, I think on MacOS by default you would get a narrow python build.  Since we use wide builds (on linux) our tooling isn't really set up completely for narrow builds, unfortunately.

Can you check your python installation and see?  If that's the issue probably your quickest workaround is to install/build  python with ucs4 support.

**Comment by jorgeliecer** [comment] 2016-09-08 00:32
Thanks for your response @dougfelt this is my configuration:

Python 2.7.12 (default, Sep  7 2016, 13:47:38) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin

OSX El capitan.

Going to remove this version using homebrew and try to install other version.. which do you recommend or try to enable  ucs4 manually.

**Comment by dougfelt** [comment] 2016-09-08 01:05
I don't have much experience.  My understanding is that MacPorts versions of python at 2.6 or later are built as wide builds by default.  If you're using Homebrew though that's not a great option for you, probably don't want both.

Otherwise an option is to build python yourself and configure it for wide build.  See this StackOverflow post: http://stackoverflow.com/questions/25111521/how-to-install-python-on-mac-with-wide-build

**Comment by jorgeliecer** [comment] 2016-09-08 02:25
Hello @dougfelt yes i did the installation but now i got this error:

Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/Volumes/Crabdisk/investigations/text2emoji/noto/noto-emoji/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "/usr/local/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/font_data.py", line 21, in <module>
    from nototools import opentype_data
  File "/usr/local/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/opentype_data.py", line 22, in <module>
    from nototools import unicode_data
  File "/usr/local/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/unicode_data.py", line 36, in <module>
    from fontTools.misc.py23 import unichr
ImportError: cannot import name unichr
make: *** No rule to make target `NotoColorEmoji.tmpl.ttf', needed by `NotoColorEmoji.ttf'.  Stop.

**Comment by dougfelt** [comment] 2016-09-09 01:03
Looks like you don't have fontTools installed.  The readme.md file doesn't mention this dependency, urg.

You can get it from here: https://github.com/behdad/fonttools.git

**Comment by jorgeliecer** [comment] 2016-09-11 15:03
Ok Done i did it. I got the font but now i will prepare a document explaining my journey and how i did... but now the font looks like damaged i cant show any icon there is any special configuration not even recognize by Font Book. 

Chrome says: Failed to decode downloaded font.

**Comment by jungshik** [comment] 2016-09-24 16:42
No browser on Mac supports Google-format color font at the moment. Chrome and Safari support only Apple format color fonts. Firefox supports SVG color fonts as well.

**Comment by marekjez86** [comment] 2016-09-26 20:07
@jorgeliecer : any update on your experience?

**Comment by dougfelt** [comment] 2016-10-17 16:10
I'm going to close this bug and link it to #72 since the problem is now the fact that MacOS doesn't support the color glyph format we use.

**Closed by dougfelt** 2016-10-17 16:10 UTC
